/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_allever_social_foke_NativeRuntime */

#ifndef _Included_com_allever_social_foke_NativeRuntime
#define _Included_com_allever_social_foke_NativeRuntime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_allever_social_foke_NativeRuntime
 * Method:    startActivity
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_allever_social_foke_NativeRuntime_startActivity
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_allever_social_foke_NativeRuntime
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_allever_social_foke_NativeRuntime_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_allever_social_foke_NativeRuntime
 * Method:    startService
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_allever_social_foke_NativeRuntime_startService
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_allever_social_foke_NativeRuntime
 * Method:    findProcess
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_allever_social_foke_NativeRuntime_findProcess
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_allever_social_foke_NativeRuntime
 * Method:    stopService
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_allever_social_foke_NativeRuntime_stopService
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
